---
- name: Manage Ubuntu EC2 instances
  hosts: ubuntu
  become: yes
  tasks:
    - name: Check if the apt keyrings directory exists
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'
    
    - name: Add Docker official GPG key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'
    
    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch={{ ansible_architecture | regex_replace('x86_64','amd64') }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        filename: docker.list
    
    - name: Update and upgrade packages on Ubuntu
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install official Docker packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: latest
    
    - name: Add ubuntu to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Check disk usage on Ubuntu
      command: df -h
      register: disk_usage

    - name: Display disk usage for Ubuntu
      debug:
        var: disk_usage.stdout_lines

- name: Manage Amazon Linux EC2 instances
  hosts: amazon
  become: yes
  tasks:
    - name: Update and upgrade packages on Amazon Linux
      dnf:
        name: '*'
        state: latest

    - name: Ensure the latest Docker is installed on Amazon Linux
      dnf:
        name: docker
        state: latest

    - name: Check disk usage on Amazon Linux
      command: df -h
      register: disk_usage

    - name: Display disk usage for Amazon Linux
      debug:
        var: disk_usage.stdout_lines
